version: '3.9'
services:
  linux:
    container_name: "ubuntu-linux"
    image: "jameszokah/ubuntu-metap"
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3333:3333"
